import { Montserrat } from "next/font/google"
import { ReduxProvider } from '@/components/providers/ReduxProvider'
import { ColorSchemeScript, mantineHtmlProps } from '@mantine/core'
import ProvideUI from '@/components/providers/ProvideUI'
import LanguageProvider from '@/components/providers/LanguageProvider'
import { headers } from 'next/headers'

// css mantine
import '@mantine/core/styles.layer.css'
import '@mantine/notifications/styles.css'
import '@mantine/dates/styles.css'
// import 'mantine-datatable/styles.layer.css'
// import '@/assets/css/table-mantine.css'

const montserratFont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata = {
  title: "Teman HR",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  const defaultLanguage = 'id'
  const headersList = await headers()
  const locale = headersList.get('x-lang') || defaultLanguage

  return (
    <html lang={locale} className={`${montserratFont.variable}`} {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${montserratFont.variable}`}>
        <ReduxProvider>
          <ProvideUI>
            <LanguageProvider>
              {children}
            </LanguageProvider>
          </ProvideUI>
        </ReduxProvider>
      </body>
    </html>
  );
}
